<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/order/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:58:25 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Order')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orders.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$order->id}}</td></tr>
		<tr><th>Customer Id</th><td>{{$order->customer_id}}</td></tr>
		<tr><th>Order Date</th><td>{{$order->order_date}}</td></tr>
		<tr><th>Delivery Date</th><td>{{$order->delivery_date}}</td></tr>
		<tr><th>Shipping Address</th><td>{{$order->shipping_address}}</td></tr>
		<tr><th>Order Total</th><td>{{$order->order_total}}</td></tr>
		<tr><th>Paid Amount</th><td>{{$order->paid_amount}}</td></tr>
		<tr><th>Remark</th><td>{{$order->remark}}</td></tr>
		<tr><th>Status Id</th><td>{{$order->status_id}}</td></tr>
		<tr><th>Discount</th><td>{{$order->discount}}</td></tr>
		<tr><th>Vat</th><td>{{$order->vat}}</td></tr>
		<tr><th>Created At</th><td>{{$order->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$order->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
