<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/role/_show.blade.php" was generated by ProBot AI.
* Date: 3/16/2025 9:36:54 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Role')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('roles.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$role->id}}</td></tr>
		<tr><th>Name</th><td>{{$role->name}}</td></tr>
		<tr><th>Updated At</th><td>{{$role->updated_at}}</td></tr>
		<tr><th>Created At</th><td>{{$role->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
