<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/producttype/_edit.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:39:50 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit ProductType')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('producttypes.index')}}">Manage</a>
<form action="{{route('producttypes.update',$producttype)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
