<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/producttype/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:39:50 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage ProductType')
@section('style')


@endsection
@section('page')
<a href="{{route('producttypes.create')}}">New ProductType</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($producttypes as $producttype)
		<tr>

			<td>
			<form action = "{{route('producttypes.destroy',$producttype->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('producttypes.show',$producttype->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('producttypes.edit',$producttype->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
