<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/producttype/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:39:50 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show ProductType')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('producttypes.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>

</tbody>
</table>
@endsection
@section('script')


@endsection
