<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/accountgroup/_index.blade.php" was generated by ProBot AI.
* Date: 2/24/2025 12:04:55 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage AccountGroup')
@section('style')


@endsection
@section('page')
<a href="{{route('accountgroups.create')}}">New AccountGroup</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Code</th>
			<th>Name</th>
			<th>Description</th>
			<th>Parent Id</th>
			<th>Is Active</th>
			<th>System Generated</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($accountgroups as $accountgroup)
		<tr>
			<td>{{$accountgroup->id}}</td>
			<td>{{$accountgroup->code}}</td>
			<td>{{$accountgroup->name}}</td>
			<td>{{$accountgroup->description}}</td>
			<td>{{$accountgroup->parent_id}}</td>
			<td>{{$accountgroup->is_active}}</td>
			<td>{{$accountgroup->system_generated}}</td>
			<td>{{$accountgroup->created_at}}</td>
			<td>{{$accountgroup->updated_at}}</td>

			<td>
			<form action = "{{route('accountgroups.destroy',$accountgroup->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('accountgroups.show',$accountgroup->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('accountgroups.edit',$accountgroup->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
