<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/order/_edit.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:58:25 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Order')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orders.index')}}">Manage</a>
<form action="{{route('orders.update',$order)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
	<div class="col-sm-10">
		<select class="form-control" name="customer_id" id="customer_id">
			@foreach($customers as $customer)
				@if($customer->id==$order->customer_id)
					<option value="{{$customer->id}}" selected>{{$customer->name}}</option>
				@else
					<option value="{{$customer->id}}">{{$customer->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="shipping_address" class="col-sm-2 col-form-label">Shipping Address</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="shipping_address" value="{{$order->shipping_address}}" id="shipping_address" placeholder="Shipping Address">
	</div>
</div>
<div class="row mb-3">
	<label for="order_total" class="col-sm-2 col-form-label">Order Total</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="order_total" value="{{$order->order_total}}" id="order_total" placeholder="Order Total">
	</div>
</div>
<div class="row mb-3">
	<label for="paid_amount" class="col-sm-2 col-form-label">Paid Amount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="paid_amount" value="{{$order->paid_amount}}" id="paid_amount" placeholder="Paid Amount">
	</div>
</div>
<div class="row mb-3">
	<label for="remark" class="col-sm-2 col-form-label">Remark</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="remark" value="{{$order->remark}}" id="remark" placeholder="Remark">
	</div>
</div>
<div class="row mb-3">
	<label for="status_id" class="col-sm-2 col-form-label">Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="status_id" id="status_id">
			@foreach($status as $status)
				@if($status->id==$order->status_id)
					<option value="{{$status->id}}" selected>{{$status->name}}</option>
				@else
					<option value="{{$status->id}}">{{$status->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="discount" class="col-sm-2 col-form-label">Discount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount" value="{{$order->discount}}" id="discount" placeholder="Discount">
	</div>
</div>
<div class="row mb-3">
	<label for="vat" class="col-sm-2 col-form-label">Vat</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="vat" value="{{$order->vat}}" id="vat" placeholder="Vat">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
