<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/uom/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:38:27 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Uom')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('uoms.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$uom->id}}</td></tr>
		<tr><th>Name</th><td>{{$uom->name}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
