<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customer/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 9:55:31 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Customer')
@section('style')


@endsection
@section('page')
<a href="{{route('customers.create')}}">New Customer</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Mobile</th>
			<th>Email</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>Address</th>
			<th>Photo</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($customers as $customer)
		<tr>
			<td>{{$customer->id}}</td>
			<td>{{$customer->name}}</td>
			<td>{{$customer->mobile}}</td>
			<td>{{$customer->email}}</td>
			<td>{{$customer->created_at}}</td>
			<td>{{$customer->updated_at}}</td>
			<td>{{$customer->address}}</td>
			<td><img src="{{asset('img/'.$customer->photo)}}" width="100" /></td>

			<td>
			<form action = "{{route('customers.destroy',$customer->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('customers.show',$customer->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('customers.edit',$customer->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
