<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/account/_create.blade.php" was generated by ProBot AI.
* Date: 2/24/2025 12:04:31 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Account')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('accounts.index')}}">Manage</a>
<form action="{{route('accounts.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="code" class="col-sm-2 col-form-label">Code</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="code" id="code" placeholder="Code">
	</div>
</div>
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="account_group_id" class="col-sm-2 col-form-label">Account_Group</label>
	<div class="col-sm-10">
		<select class="form-control" name="account_group_id" id="account_group_id">
			@foreach($account_groups as $account_group)
				<option value="{{$account_group->id}}">{{$account_group->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="is_payment_method" class="col-sm-2 col-form-label">Is Payment Method</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="is_payment_method" id="is_payment_method" placeholder="Is Payment Method">
	</div>
</div>
<div class="row mb-3">
	<label for="is_trx_no_required" class="col-sm-2 col-form-label">Is Trx No Required</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="is_trx_no_required" id="is_trx_no_required" placeholder="Is Trx No Required">
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="description" id="description" placeholder="Description"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="is_active" class="col-sm-2 col-form-label">Is Active</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="is_active" id="is_active" placeholder="Is Active">
	</div>
</div>
<div class="row mb-3">
	<label for="created_by" class="col-sm-2 col-form-label">Created By</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="created_by" id="created_by" placeholder="Created By">
	</div>
</div>
<div class="row mb-3">
	<label for="updated_by" class="col-sm-2 col-form-label">Updated By</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="updated_by" id="updated_by" placeholder="Updated By">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
