<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_StockController.php" was generated by ProBot AI.
* Date: 2/22/2025 10:47:23 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Stock;
use App\Models\Product;
use App\Models\Transaction_Type;
use App\Models\Warehouse;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class StockController extends Controller{
	public function index(){
		$stocks = Stock::paginate(10);
		return view("pages.erp.stock.index",["stocks"=>$stocks]);
	}
	public function create(){
		return view("pages.erp.stock.create",["products"=>Product::all(),"transaction_types"=>Transaction_Type::all(),"warehouses"=>Warehouse::all()]);
	}
	public function store(Request $request){
		//Stock::create($request->all());
		$stock = new Stock;
		$stock->product_id=$request->product_id;
		$stock->qty=$request->qty;
		$stock->transaction_type_id=$request->transaction_type_id;
		$stock->remark=$request->remark;
        date_default_timezone_set("Asia/Dhaka");
		$stock->created_at=date('Y-m-d H:i:s');
		$stock->warehouse_id=$request->warehouse_id;

		$stock->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$stock = Stock::find($id);
		return view("pages.erp.stock.show",["stock"=>$stock]);
	}
	public function edit(Stock $stock){
		return view("pages.erp.stock.edit",["stock"=>$stock,"products"=>Product::all(),"transaction_types"=>Transaction_Type::all(),"warehouses"=>Warehouse::all()]);
	}
	public function update(Request $request,Stock $stock){
		//Stock::update($request->all());
		$stock = Stock::find($stock->id);
		$stock->product_id=$request->product_id;
		$stock->qty=$request->qty;
		$stock->transaction_type_id=$request->transaction_type_id;
		$stock->remark=$request->remark;
date_default_timezone_set("Asia/Dhaka");
		$stock->created_at=date('Y-m-d H:i:s');
		$stock->warehouse_id=$request->warehouse_id;

		$stock->save();

		return redirect()->route("stocks.index")->with('success','Updated Successfully.');
	}
	public function destroy(Stock $stock){
		$stock->delete();
		return redirect()->route("stocks.index")->with('success', 'Deleted Successfully.');
	}
}
?>
