<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_UserController.php" was generated by ProBot AI.
* Date: 4/6/2025 9:18:09 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Role;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class UserController extends Controller{
	public function index(){
		$users = User::paginate(10);
		return view("pages.erp.user.index",["users"=>$users]);
	}
	public function create(){
		return view("pages.erp.user.create",["roles"=>Role::all()]);
	}
	public function store(Request $request){
		//User::create($request->all());
		$user = new User;
		$user->name=$request->name;
		$user->role_id=$request->role_id;
		$user->password=$request->password;
		$user->email=$request->email;
		$user->full_name=$request->full_name;
        date_default_timezone_set("Asia/Dhaka");
		$user->created_at=date('Y-m-d H:i:s');
		if(isset($request->photo)){
			$user->photo=$request->photo;
		}
		$user->verify_code=$request->verify_code;
		$user->inactive=$request->inactive;
		$user->mobile=$request->mobile;
         date_default_timezone_set("Asia/Dhaka");
		$user->updated_at=date('Y-m-d H:i:s');
		$user->ip=$request->ip;
		$user->email_verified_at=$request->email_verified_at;
		$user->remember_token=$request->remember_token;

		$user->save();
		if(isset($request->photo)){
			$imageName=$user->id.'.'.$request->photo->extension();
			$user->photo=$imageName;
			$user->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$user = User::find($id);
		return view("pages.erp.user.show",["user"=>$user]);
	}
	public function edit(User $user){
		return view("pages.erp.user.edit",["user"=>$user,"roles"=>Role::all()]);
	}
	public function update(Request $request,User $user){
		//User::update($request->all());
		$user = User::find($user->id);
		$user->name=$request->name;
		$user->role_id=$request->role_id;
		$user->password=$request->password;
		$user->email=$request->email;
		$user->full_name=$request->full_name;
date_default_timezone_set("Asia/Dhaka");
		$user->created_at=date('Y-m-d H:i:s');
		if(isset($request->photo)){
			$user->photo=$request->photo;
		}
		$user->verify_code=$request->verify_code;
		$user->inactive=$request->inactive;
		$user->mobile=$request->mobile;
date_default_timezone_set("Asia/Dhaka");
		$user->updated_at=date('Y-m-d H:i:s');
		$user->ip=$request->ip;
		$user->email_verified_at=$request->email_verified_at;
		$user->remember_token=$request->remember_token;

		$user->save();
		if(isset($request->photo)){
			$imageName=$user->id.'.'.$request->photo->extension();
			$user->photo=$imageName;
			$user->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("users.index")->with('success','Updated Successfully.');
	}
	public function destroy(User $user){
		$user->delete();
		return redirect()->route("users.index")->with('success', 'Deleted Successfully.');
	}
}
?>
