<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AccountController.php" was generated by ProBot AI.
* Date: 2/24/2025 12:04:30 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Account;
use App\Models\Account_Group;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AccountController extends Controller{
	public function index(){
		$accounts = Account::paginate(10);
		return view("pages.erp.account.index",["accounts"=>$accounts]);
	}
	public function create(){
		return view("pages.erp.account.create",["account_groups"=>Account_Group::all()]);
	}
	public function store(Request $request){
		//Account::create($request->all());
		$account = new Account;
		$account->code=$request->code;
		$account->name=$request->name;
		$account->account_group_id=$request->account_group_id;
		$account->is_payment_method=$request->is_payment_method;
		$account->is_trx_no_required=$request->is_trx_no_required;
		$account->description=$request->description;
		$account->is_active=$request->is_active;
date_default_timezone_set("Asia/Dhaka");
		$account->created_at=date('Y-m-d H:i:s');
		$account->created_by=$request->created_by;
date_default_timezone_set("Asia/Dhaka");
		$account->updated_at=date('Y-m-d H:i:s');
		$account->updated_by=$request->updated_by;

		$account->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$account = Account::find($id);
		return view("pages.erp.account.show",["account"=>$account]);
	}
	public function edit(Account $account){
		return view("pages.erp.account.edit",["account"=>$account,"account_groups"=>Account_Group::all()]);
	}
	public function update(Request $request,Account $account){
		//Account::update($request->all());
		$account = Account::find($account->id);
		$account->code=$request->code;
		$account->name=$request->name;
		$account->account_group_id=$request->account_group_id;
		$account->is_payment_method=$request->is_payment_method;
		$account->is_trx_no_required=$request->is_trx_no_required;
		$account->description=$request->description;
		$account->is_active=$request->is_active;
date_default_timezone_set("Asia/Dhaka");
		$account->created_at=date('Y-m-d H:i:s');
		$account->created_by=$request->created_by;
date_default_timezone_set("Asia/Dhaka");
		$account->updated_at=date('Y-m-d H:i:s');
		$account->updated_by=$request->updated_by;

		$account->save();

		return redirect()->route("accounts.index")->with('success','Updated Successfully.');
	}
	public function destroy(Account $account){
		$account->delete();
		return redirect()->route("accounts.index")->with('success', 'Deleted Successfully.');
	}
}
?>
