<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AccountTypeController.php" was generated by ProBot AI.
* Date: 2/24/2025 12:05:05 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\AccountType;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AccountTypeController extends Controller{
	public function index(){
		$accounttypes = AccountType::paginate(10);
		return view("pages.erp.accounttype.index",["accounttypes"=>$accounttypes]);
	}
	public function create(){
		return view("pages.erp.accounttype.create",[]);
	}
	public function store(Request $request){
		//AccountType::create($request->all());
		$accounttype = new AccountType;
		$accounttype->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$accounttype->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$accounttype->updated_at=date('Y-m-d H:i:s');

		$accounttype->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$accounttype = AccountType::find($id);
		return view("pages.erp.accounttype.show",["accounttype"=>$accounttype]);
	}
	public function edit(AccountType $accounttype){
		return view("pages.erp.accounttype.edit",["accounttype"=>$accounttype,]);
	}
	public function update(Request $request,AccountType $accounttype){
		//AccountType::update($request->all());
		$accounttype = AccountType::find($accounttype->id);
		$accounttype->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$accounttype->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$accounttype->updated_at=date('Y-m-d H:i:s');

		$accounttype->save();

		return redirect()->route("accounttypes.index")->with('success','Updated Successfully.');
	}
	public function destroy(AccountType $accounttype){
		$accounttype->delete();
		return redirect()->route("accounttypes.index")->with('success', 'Deleted Successfully.');
	}
}
?>
