<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_LotController.php" was generated by ProBot AI.
* Date: 2/27/2025 12:00:08 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Lot;
use App\Models\Product;
use App\Models\Warehouse;
use App\Models\Transaction_Type;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class LotController extends Controller{
	public function index(){
		$lots = Lot::paginate(10);
		return view("pages.erp.lot.index",["lots"=>$lots]);
	}
	public function create(){
		return view("pages.erp.lot.create",["products"=>Product::all(),"warehouses"=>Warehouse::all(),"transaction_types"=>Transaction_Type::all()]);
	}
	public function store(Request $request){
		//Lot::create($request->all());
		$lot = new Lot;
		$lot->product_id=$request->product_id;
		$lot->quantity=$request->quantity;
		$lot->cost_price=$request->cost_price;
		$lot->sales_price=$request->sales_price;
		$lot->warehouse_id=$request->warehouse_id;
		$lot->transaction_type_id=$request->transaction_type_id;
		$lot->description=$request->description;
        date_default_timezone_set("Asia/Dhaka");
		$lot->created_at=date('Y-m-d H:i:s');
        date_default_timezone_set("Asia/Dhaka");
		$lot->updated_at=date('Y-m-d H:i:s');

		$lot->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$lot = Lot::find($id);
		return view("pages.erp.lot.show",["lot"=>$lot]);
	}
	public function edit(Lot $lot){
		return view("pages.erp.lot.edit",["lot"=>$lot,"products"=>Product::all(),"warehouses"=>Warehouse::all(),"transaction_types"=>Transaction_Type::all()]);
	}
	public function update(Request $request,Lot $lot){
		//Lot::update($request->all());
		$lot = Lot::find($lot->id);
		$lot->product_id=$request->product_id;
		$lot->quantity=$request->quantity;
		$lot->cost_price=$request->cost_price;
		$lot->sales_price=$request->sales_price;
		$lot->warehouse_id=$request->warehouse_id;
		$lot->transaction_type_id=$request->transaction_type_id;
		$lot->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$lot->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$lot->updated_at=date('Y-m-d H:i:s');

		$lot->save();

		return redirect()->route("lots.index")->with('success','Updated Successfully.');
	}
	public function destroy(Lot $lot){
		$lot->delete();
		return redirect()->route("lots.index")->with('success', 'Deleted Successfully.');
	}
}
?>
