<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_OrderDetailController.php" was generated by ProBot AI.
* Date: 2/22/2025 9:28:15 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\OrderDetail;
use App\Models\Order;
use App\Models\Product;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class OrderDetailController extends Controller{
	public function index(){
		$orderdetails = OrderDetail::paginate(10);
		return view("pages.erp.orderdetail.index",["orderdetails"=>$orderdetails]);
	}
	public function create(){
		return view("pages.erp.orderdetail.create",["orders"=>Order::all(),"products"=>Product::all()]);
	}
	public function store(Request $request){
		//OrderDetail::create($request->all());
		$orderdetail = new OrderDetail;
		$orderdetail->order_id=$request->order_id;
		$orderdetail->product_id=$request->product_id;
		$orderdetail->qty=$request->qty;
		$orderdetail->price=$request->price;
		$orderdetail->vat=$request->vat;
		$orderdetail->discount=$request->discount;
        date_default_timezone_set("Asia/Dhaka");
		$orderdetail->created_at=date('Y-m-d H:i:s');
         date_default_timezone_set("Asia/Dhaka");
		$orderdetail->updated_at=date('Y-m-d H:i:s');

		$orderdetail->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$orderdetail = OrderDetail::find($id);
		return view("pages.erp.orderdetail.show",["orderdetail"=>$orderdetail]);
	}
	public function edit(OrderDetail $orderdetail){
		return view("pages.erp.orderdetail.edit",["orderdetail"=>$orderdetail,"orders"=>Order::all(),"products"=>Product::all()]);
	}
	public function update(Request $request,OrderDetail $orderdetail){
		//OrderDetail::update($request->all());
		$orderdetail = OrderDetail::find($orderdetail->id);
		$orderdetail->order_id=$request->order_id;
		$orderdetail->product_id=$request->product_id;
		$orderdetail->qty=$request->qty;
		$orderdetail->price=$request->price;
		$orderdetail->vat=$request->vat;
		$orderdetail->discount=$request->discount;
date_default_timezone_set("Asia/Dhaka");
		$orderdetail->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$orderdetail->updated_at=date('Y-m-d H:i:s');

		$orderdetail->save();

		return redirect()->route("orderdetails.index")->with('success','Updated Successfully.');
	}
	public function destroy(OrderDetail $orderdetail){
		$orderdetail->delete();
		return redirect()->route("orderdetails.index")->with('success', 'Deleted Successfully.');
	}
}
?>
