<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ProductTypeController.php" was generated by ProBot AI.
* Date: 2/19/2025 9:38:59 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\ProductType;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ProductTypeController extends Controller{
	public function index(){
		$producttypes = ProductType::paginate(10);
		return view("pages.erp.producttype.index",["producttypes"=>$producttypes]);
	}
	public function create(){
		return view("pages.erp.producttype.create",[]);
	}
	public function store(Request $request){
		//ProductType::create($request->all());
		$producttype = new ProductType;

		$producttype->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$producttype = ProductType::find($id);
		return view("pages.erp.producttype.show",["producttype"=>$producttype]);
	}
	public function edit(ProductType $producttype){
		return view("pages.erp.producttype.edit",["producttype"=>$producttype,]);
	}
	public function update(Request $request,ProductType $producttype){
		//ProductType::update($request->all());
		$producttype = ProductType::find($producttype->id);

		$producttype->save();

		return redirect()->route("producttypes.index")->with('success','Updated Successfully.');
	}
	public function destroy(ProductType $producttype){
		$producttype->delete();
		return redirect()->route("producttypes.index")->with('success', 'Deleted Successfully.');
	}
}
?>
