<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ProductSectionController.php" was generated by ProBot AI.
* Date: 2/19/2025 9:39:59 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\ProductSection;
use App\Models\Unit;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ProductSectionController extends Controller{
	public function index(){
		$productsections = ProductSection::paginate(10);
		return view("pages.erp.productsection.index",["productsections"=>$productsections]);
	}
	public function create(){
		return view("pages.erp.productsection.create",["units"=>Unit::all()]);
	}
	public function store(Request $request){
		//ProductSection::create($request->all());
		$productsection = new ProductSection;
		$productsection->name=$request->name;
		$productsection->unit_id=$request->unit_id;
		if(isset($request->photo)){
			$productsection->photo=$request->photo;
		}
		$productsection->icon=$request->icon;

		$productsection->save();
		if(isset($request->photo)){
			$imageName=$productsection->id.'.'.$request->photo->extension();
			$productsection->photo=$imageName;
			$productsection->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$productsection = ProductSection::find($id);
		return view("pages.erp.productsection.show",["productsection"=>$productsection]);
	}
	public function edit(ProductSection $productsection){
		return view("pages.erp.productsection.edit",["productsection"=>$productsection,"units"=>Unit::all()]);
	}
	public function update(Request $request,ProductSection $productsection){
		//ProductSection::update($request->all());
		$productsection = ProductSection::find($productsection->id);
		$productsection->name=$request->name;
		$productsection->unit_id=$request->unit_id;
		if(isset($request->photo)){
			$productsection->photo=$request->photo;
		}
		$productsection->icon=$request->icon;

		$productsection->save();
		if(isset($request->photo)){
			$imageName=$productsection->id.'.'.$request->photo->extension();
			$productsection->photo=$imageName;
			$productsection->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("productsections.index")->with('success','Updated Successfully.');
	}
	public function destroy(ProductSection $productsection){
		$productsection->delete();
		return redirect()->route("productsections.index")->with('success', 'Deleted Successfully.');
	}
}
?>
