<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_RoleController.php" was generated by ProBot AI.
* Date: 3/16/2025 9:36:52 AM
* Contact: towhid1@outlook.com
*/

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Role;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class RoleController extends Controller
{
	public function index()
	{
		$roles = Role::paginate(10);
		return response()->json(["roles" => $roles]);
	}
	public function create()
	{
		return view("pages.erp.role.create", []);
	}
	public function store(Request $request)
	{

		print_r($request->all());

		try {
			//Role::create($request->all());
		$role = new Role;
		$role->name = $request->name;
		date_default_timezone_set("Asia/Dhaka");
		$role->updated_at = date('Y-m-d H:i:s');
		date_default_timezone_set("Asia/Dhaka");
		$role->created_at = date('Y-m-d H:i:s');

		$role->save();

		 return response()->json(["message" => "Role Saved successfully", "role" => $role ]);
		} catch (\Throwable $th) {
			return response()->json(["message" => $th->getMessage()] );
		}
		
	}
	public function show($id)
	{
		$role = Role::find($id);
		return response()->json(["role" => $role]);
	}
	public function edit(Role $role)
	{
		return view("pages.erp.role.edit", ["role" => $role,]);
	}
	public function update(Request $request)
	{
		// print_r($request->all());
		//Role::update($request->all());

		try {
			$role = Role::find($request->id);
			$role->name = $request->name;
			date_default_timezone_set("Asia/Dhaka");
			$role->updated_at = date('Y-m-d H:i:s');
			date_default_timezone_set("Asia/Dhaka");
			$role->created_at = date('Y-m-d H:i:s');
			$role->save();

			return response()->json(["role" => $role]);
		} catch (\Throwable $th) {
			return response()->json(["role" => $th]);
		}
	}
	public function destroy(Request $request)
	{
		try {
			$role = Role::find($request->id);
			if ($role) {
				$role->delete();
				return response()->json(["message" => "Role deleted successfully", "role" => $request->id]);
			}
			return response()->json(["error" => "Role not found"], 404);
		} catch (\Throwable $th) {
			return response()->json(["error" => $th->getMessage()], 500);
		}
	}

	public function delete(Request $request)
	{
		try {
			$role = Role::find($request->id);
			if ($role) {
				$role->delete();
				return response()->json(["message" => "Role deleted successfully", "role" => $request->id]);
			}
			return response()->json(["error" => "Role not found"], 404);
		} catch (\Throwable $th) {
			return response()->json(["error" => $th->getMessage()], 500);
		}
	}
}
