<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Account.php" was generated by ProBot AI.
* Date: 2/24/2025 12:04:31 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Account extends Model{


}
?>
