<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_AccountGroup.php" was generated by ProBot AI.
* Date: 2/24/2025 12:04:55 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AccountGroup extends Model{


     function parent(){
         return $this->belongsTo(AccountGroup::class, 'parent_id');
     }


     public function children()
     {
         return $this->hasMany(AccountGroup::class, 'parent_id');
     }


     function accounts(){
         return $this->hasMany(Account::class, 'account_group_id');
     }

}
?>
