<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_AccountType.php" was generated by ProBot AI.
* Date: 2/24/2025 12:05:07 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class AccountType extends Model{


}
?>
