<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_ProductSection.php" was generated by ProBot AI.
* Date: 2/19/2025 9:40:01 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class ProductSection extends Model{


}
?>
