<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_ProductType.php" was generated by ProBot AI.
* Date: 2/19/2025 9:39:50 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class ProductType extends Model{


}
?>
