<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/accounttype/_index.blade.php" was generated by ProBot AI.
* Date: 2/24/2025 12:05:07 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage AccountType')
@section('style')


@endsection
@section('page')
<a href="{{route('accounttypes.create')}}">New AccountType</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($accounttypes as $accounttype)
		<tr>
			<td>{{$accounttype->id}}</td>
			<td>{{$accounttype->name}}</td>
			<td>{{$accounttype->created_at}}</td>
			<td>{{$accounttype->updated_at}}</td>

			<td>
			<form action = "{{route('accounttypes.destroy',$accounttype->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('accounttypes.show',$accounttype->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('accounttypes.edit',$accounttype->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
