<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/accounttype/_show.blade.php" was generated by ProBot AI.
* Date: 2/24/2025 12:05:07 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show AccountType')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('accounttypes.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$accounttype->id}}</td></tr>
		<tr><th>Name</th><td>{{$accounttype->name}}</td></tr>
		<tr><th>Created At</th><td>{{$accounttype->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$accounttype->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
