<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/service/_create.blade.php" was generated by ProBot AI.
* Date: 2/24/2025 10:55:00 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Service')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('services.index')}}">Manage</a>
<form action="{{route('services.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="id" class="col-sm-2 col-form-label">Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="id" id="id" placeholder="Id">
	</div>
</div>
<div class="row mb-3">
	<label for="category_id" class="col-sm-2 col-form-label">Category Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="category_id" id="category_id" placeholder="Category Id">
	</div>
</div>
<div class="row mb-3">
	<label for="sub_category_id" class="col-sm-2 col-form-label">Sub Category Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="sub_category_id" id="sub_category_id" placeholder="Sub Category Id">
	</div>
</div>
<div class="row mb-3">
	<label for="provider_id" class="col-sm-2 col-form-label">Provider Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="provider_id" id="provider_id" placeholder="Provider Id">
	</div>
</div>
<div class="row mb-3">
	<label for="title" class="col-sm-2 col-form-label">Title</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="title" id="title" placeholder="Title">
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="description" id="description" placeholder="Description"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="status_id" class="col-sm-2 col-form-label">Status Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="status_id" id="status_id" placeholder="Status Id">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
